name: Build ArzabcWG APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: |
          # Используем NDK, который уже есть в системе (обычно это 25.x или 26.x)
          export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk-bundle
          
          # Создаем local.properties автоматически с правильными путями
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ndk.dir=$ANDROID_SDK_ROOT/ndk-bundle" >> local.properties
          
          # Настраиваем PATH для Go
          export PATH=$PATH:$(go env GOPATH)/bin
          
          # Собираем
          ./gradlew assembleDebug -x lint --no-daemon -Dorg.gradle.parallel=false -Dorg.gradle.workers.max=1

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ArzabcWG-Debug-File
          path: "**/build/outputs/apk/debug/*.apk"
