name: Build ArzabcWG APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Устанавливаем конкретную версию NDK, которую любит WireGuard
      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.1.10909125"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        # Указываем путь к NDK через переменную окружения
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/26.1.10909125
        run: ./gradlew assembleDebug -x lint
