name: Build ArzabcWG APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: |
          # Находим путь к последнему установленному NDK автоматически
          NDK_PATH=$(find $ANDROID_SDK_ROOT/ndk -maxdepth 1 -type d | sort -V | tail -n 1)
          echo "Found NDK at: $NDK_PATH"
          
          # Записываем его в local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ndk.dir=$NDK_PATH" >> local.properties
          
          # Настраиваем PATH для Go
          export PATH=$PATH:$(go env GOPATH)/bin
          
          # Сборка с ограничением ресурсов для стабильности
          ./gradlew assembleDebug -x lint --no-daemon -Dorg.gradle.parallel=false -Dorg.gradle.workers.max=1

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ArzabcWG-Debug-File
          path: "**/build/outputs/apk/debug/*.apk"
